{
  "name": "American Avalanche Association",
  "description": "SNOW, WEATHER, AND AVALANCHES: Observation Guidelines for Avalanche Programs in the United States",
  "version": "6.0.0",
  "author": "IonicThemes",
  "contributors": [
    "Dayana <dayana@ionicthemes.com>",
    "Agustín <agustin@ionicthemes.com>"
  ],
  "homepage": "https://americanavalancheassociation.com/",
  "private": true,
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint"
  },
  "dependencies": {
    "@angular/animations": "^16.1.3",
    "@angular/common": "^16.1.3",
    "@angular/core": "^16.1.3",
    "@angular/fire": "^7.6.1",
    "@angular/forms": "^16.1.3",
    "@angular/platform-browser": "^16.1.3",
    "@angular/platform-browser-dynamic": "^16.1.3",
    "@angular/router": "^16.1.3",
    "@angular/service-worker": "^16.1.3",
    "@awesome-cordova-plugins/file": "^6.3.0",
    "@capacitor-firebase/authentication": "^1.3.0",
    "@capacitor/android": "^4.0.0",
    "@capacitor/app": "^4.0.0",
    "@capacitor/core": "^4.0.0",
    "@capacitor/geolocation": "^4.0.0",
    "@capacitor/haptics": "^4.0.0",
    "@capacitor/ios": "^4.0.0",
    "@capacitor/keyboard": "^4.0.0",
    "@capacitor/preferences": "^4.0.2",
    "@capacitor/share": "^4.0.0",
    "@capacitor/splash-screen": "^4.0.0",
    "@capacitor/status-bar": "^4.0.0",
    "@ionic/angular": "^6.5.0",
    "@ionic/storage": "^4.0.0",
    "@ionic/storage-angular": "^4.0.0",
    "@types/core-js": "^2.5.5",
    "angular-pipes": "^10.0.0",
    "bootstrap": "^5.3.0",
    "cordova-plugin-file": "^7.0.0",
    "core-js": "^2.6.12",
    "dayjs": "^1.11.7",
    "firebase": "^9.23.0",
    "google-libphonenumber": "^3.2.31",
    "jquery": "^3.7.0",
    "rxjs": "^7.8.0",
    "swiper": "^8.4.6",
    "tslib": "^2.4.1",
    "zone.js": "^0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1601.3",
    "@angular-devkit/build-angular": "^16.1.3",
    "@angular-devkit/core": "^16.1.3",
    "@angular-devkit/schematics": "^16.1.3",
    "@angular-eslint/builder": "16.0.3",
    "@angular-eslint/eslint-plugin": "16.0.3",
    "@angular-eslint/eslint-plugin-template": "16.0.3",
    "@angular-eslint/schematics": "16.0.3",
    "@angular-eslint/template-parser": "16.0.3",
    "@angular/cli": "^16.1.3",
    "@angular/compiler": "^16.1.3",
    "@angular/compiler-cli": "^16.1.3",
    "@angular/language-service": "^16.1.3",
    "@capacitor/cli": "^4.0.0",
    "@commitlint/cli": "^8.2.0",
    "@commitlint/config-angular": "^17.4.2",
    "@ionic/angular-toolkit": "^7.0.0",
    "@ionic/cli": "6.20.8",
    "@types/node": "^17.0.45",
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "@webcomponents/webcomponentsjs": "^2.7.0",
    "cordova-res": "0.15.4",
    "eslint": "^8.39.0",
    "husky": "^4.3.0",
    "ts-node": "^8.10.2",
    "typescript": "~5.1.6"
  }
}
